#-------------------------------
# General Site Settings
title: JaewonLeeDev
logo: logo.svg # You can add own logo.
description: Develope the world!


#-------------------------------
# Author Settings
author:
  name: Jaewon Lee [j]
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Jaewon Lee</strong>
  bio: <strong>Data science</strong>, <strong>life science</strong>, <strong>Dev</strong>, talks, and writes. I share Data science tutorials, AI tutorials, Dev tutorials. love music and outdoor activities.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
